unstable_features = true
tab_spaces = 2
max_width = 80
wrap_comments = true
imports_granularity = "module"
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
normalize_doc_attributes = true
format_strings = true
